# Generated by Django 5.1.3 on 2024-12-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("avg_rating", models.FloatField(default=0)),
                ("avg_difficulty", models.FloatField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professors",
                        to="uni_central.department",
                    ),
                ),
            ],
            options={
                "db_table": "professors",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("avg_difficulty", models.FloatField(default=0)),
                ("avg_rating", models.FloatField(default=0)),
                ("credits", models.PositiveIntegerField()),
                ("semester", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="uni_central.department",
                    ),
                ),
                (
                    "professors",
                    models.ManyToManyField(
                        related_name="courses", to="uni_central.professor"
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email_address", models.EmailField(max_length=255, unique=True)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="students", to="uni_central.course"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("difficulty", models.IntegerField(blank=True, null=True)),
                ("estimated_hours", models.FloatField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=2, null=True)),
                ("would_take_again", models.BooleanField(default=False)),
                ("for_credit", models.BooleanField(default=False)),
                ("mandatory_attendance", models.BooleanField(default=False)),
                ("required_course", models.BooleanField(default=False)),
                ("is_gened", models.BooleanField(default=False)),
                ("in_person", models.BooleanField(default=False)),
                ("online", models.BooleanField(default=False)),
                ("hybrid", models.BooleanField(default=False)),
                ("no_exams", models.BooleanField(default=False)),
                ("presentations", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="uni_central.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_central.professor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_central.user",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
    ]
