# Generated by Django 5.1.3 on 2025-02-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_central", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="course_plan",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="professors",
            field=models.ManyToManyField(
                related_name="students", to="uni_central.professor"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="threads", to="uni_central.course"
                    ),
                ),
                (
                    "professors",
                    models.ManyToManyField(
                        blank=True, related_name="threads", to="uni_central.professor"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="uni_central.user",
                    ),
                ),
            ],
            options={
                "db_table": "threads",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="uni_central.user",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="uni_central.thread",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
    ]
