# Generated by Django 5.1.3 on 2025-02-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_central", "0002_user_course_plan_user_major_user_professors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="professors",
        ),
        migrations.AddField(
            model_name="thread",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="uni_central.course",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="uni_central.professor",
            ),
        ),
    ]
