# Generated by Django 5.1.3 on 2025-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_central', '0003_remove_thread_courses_remove_thread_professors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('exams', 'Exams'), ('homework', 'Homework'), ('projects', 'Projects')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
