# Generated by Django 5.1.3 on 2025-04-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_central", "0005_remove_comment_upvotes_remove_thread_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uni_central.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Plan",
                "verbose_name_plural": "Course Plans",
                "db_table": "course_plans",
            },
        ),
    ]
