# Generated by Django 5.1.3 on 2025-04-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_central', '0008_alter_commentupvote_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentupvote',
            table='comment_upvotes',
        ),
    ]
