# Generated by Django 5.1.3 on 2025-04-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_central', '0006_courseplan'),
        ('uni_central', '0009_alter_commentupvote_table'),
    ]

    operations = [
    ]
