# Generated by Django 5.1.3 on 2025-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_central', '0010_merge_0006_courseplan_0009_alter_commentupvote_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('exams', 'Exams'), ('homework', 'Homework'), ('projects', 'Projects')], default='general', max_length=50),
        ),
    ]
