# Generated by Django 5.1.3 on 2025-04-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_central', '0011_thread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
