# Generated by Django 5.1.3 on 2025-04-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_central", "0012_review_is_anonymous"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyBuddyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_study_requests",
                        to="uni_central.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_study_requests",
                        to="uni_central.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Buddy Request",
                "verbose_name_plural": "Study Buddy Requests",
                "db_table": "study_buddy_requests",
                "unique_together": {("sender", "receiver", "course_name")},
            },
        ),
    ]
