# Generated by Django 5.1.3 on 2025-04-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni_central", "0013_studybuddyrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyBuddyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="uni_central.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="uni_central.user",
                    ),
                ),
                (
                    "study_buddy_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="uni_central.studybuddyrequest",
                    ),
                ),
            ],
            options={
                "db_table": "study_buddy_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
